# TinyStories-15M at batch 1 with the whole transformer on the Coral Edge TPU: ONE program call per token runs all 6 layers (RMSNorms,
# attention with RoPE over the KV cache, residuals, FFNs), generated by our own code generator (coral/codegen/layer.py; edgetpu_compiler
# can't compile any of it). The host keeps the embedding lookup, the final RMSNorm + classifier (32000 x 288, numpy), the sampling and
# the uint8 KV cache:
#   token -> embedding -> quantize -> [one TPU call: 6 layers] -> x_out, k'|v of every layer -> dequantize -> RMSNorm -> logits -> sample
#   python examples/stories_chip.py --prompt "Once upon a time" --steps 200
#   --mock       the bit model (coral.codegen.layer.model_ref, bit-exact with the device) on the host instead of the device
#   --float      the float model on the host, for comparison
#   --eval N     quality offline: teacher-forced perplexity and top-1 agreement with the float model on N stories it wrote
import sys, json, time, hashlib, pathlib, argparse
import numpy as np
ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from coral.codegen import layer as LY

class Tokenizer:
  """llama2.c's tokenizer.bin (examples/stories.py's Tokenizer, copied here so that this example doesn't import tinygrad)"""
  def __init__(self, path:pathlib.Path, vocab_size:int):
    import struct
    raw, off = path.read_bytes(), 4
    self.vocab, self.scores = [], []
    for _ in range(vocab_size):
      score, n = struct.unpack_from("fi", raw, off); off += 8
      self.vocab.append(raw[off:off+n]); self.scores.append(score); off += n
    self.lookup = {t: i for i, t in enumerate(self.vocab)}
  def encode(self, text:str) -> list[int]:
    toks = [self.lookup[b" "]] if text else []
    for ch in text.encode():
      toks.append(self.lookup[bytes([ch])] if bytes([ch]) in self.lookup else self.lookup[f"<0x{ch:02X}>".encode()])
    while True:
      best = max(((self.scores[j], i, j) for i in range(len(toks) - 1) if (j:=self.lookup.get(self.vocab[toks[i]] + self.vocab[toks[i+1]])) is not None), default=None)
      if best is None: break
      _, i, j = best; toks[i:i+2] = [j]
    return [1] + toks
  def decode(self, prev:int, tok:int) -> str:
    piece = self.vocab[tok]
    if prev == 1 and piece.startswith(b" "): piece = piece[1:]
    if piece.startswith(b"<0x") and piece.endswith(b">") and len(piece) == 6: piece = bytes([int(piece[3:5], 16)])
    return piece.decode(errors="replace")

# ***** quantization: calibrated on stories the float model writes (cached in models/, as examples/stories.py caches its ranges) *****
def calibration(w:dict, n:int=8, T:int=200, seed:int=0) -> tuple[list[dict], list[dict]]:
  """(main, bos) quantization (layer.calibrate_split) from n float stories of up to T tokens"""
  key = hashlib.sha1(f"chip {n} {T} {seed} {w['emb'].shape} {float(w['norm'].sum()):.6f}".encode()).hexdigest()[:12]
  cache = ROOT / "models" / f"calib_chip_{key}.json"
  if cache.exists():
    d = json.loads(cache.read_text())
    tup = lambda qs: [{k: tuple(v) if isinstance(v, list) else v for k, v in q.items()} for q in qs]
    return tup(d["main"]), tup(d["bos"])
  st = time.perf_counter()
  qm, qb = LY.calibrate_split(w, LY.float_stories(w, n, T, seed=seed))
  cache.write_text(json.dumps(dict(main=qm, bos=qb)))
  print(f"calibration on {n} float stories: {time.perf_counter() - st:.1f} s (cached in {cache.name})")
  return qm, qb

# ***** the programs: one per number of positions P (the new token at P-1), the same parameter placement for all *****
def _gen(args):
  P, quants, pl, local = args
  pc, bss, io = LY.gen_model(P, quants, pl, local=local)
  return P, pc, bss, io

def programs(Ps:list[int], qm:list[dict], qb:list[dict], pl:list[dict], workers:int=8, local:bool=False) -> dict:
  """{P: (caching, bitstreams, io)}: P = 1 with the BOS quantization, P >= 2 with the main one; generated in worker processes"""
  from concurrent.futures import ProcessPoolExecutor
  st = time.perf_counter()
  with ProcessPoolExecutor(workers) as ex: out = {P: (pc, bss, io) for P, pc, bss, io in ex.map(_gen, [(P, qb if P == 1 else qm, pl, local) for P in Ps])}
  print(f"{len(Ps)} programs (P = {min(Ps)}..{max(Ps)}) generated in {time.perf_counter() - st:.1f} s, "
        f"{np.mean([sum(len(b) for b in out[P][1]) for P in Ps]) / 1024:.0f} KB of instructions per call on average")
  return out

class Chip:
  """the model with all 6 layers on the Edge TPU (or, mock=True, the bit model on the host): step(token, pos) -> logits"""
  def __init__(self, w:dict, qm:list[dict], qb:list[dict], max_pos:int, mock:bool=False, check:str|None=None, local:bool=False, tpu=None):
    self.w, self.qm, self.qb, self.mock, self.L, self.check, self.bad = w, qm, qb, mock, len(qm), check, []
    self.Ws = LY.quant_weights(w, qm)
    self.Kh = np.zeros((self.L, 6, 256, 48), np.uint8); self.Vh = np.zeros_like(self.Kh)   # the KV cache, head-major (k' in SIGMA order)
    self.out_w, self.norm_w = np.ascontiguousarray(w["out"], np.float32), w["norm"].astype(np.float32)
    self.times = {"tpu": [], "host": []}
    if mock: return
    from coral.device import EdgeTPU
    from coral.runtime import run_executable
    pl = LY.plan(self.L)
    self.progs = programs(list(range(1, max_pos + 1)), qm, qb, pl, local=local)
    self.exes = {P: LY.model_executables(pc, bss, io)[1] for P, (pc, bss, io) in self.progs.items()}
    self.caching = LY.model_executables(*self.progs[1])[0]
    self.tpu = EdgeTPU() if tpu is None else tpu     # (examples/server.py shares coral.tpu's device)
    self.upload()
  def upload(self):
    """the parameters into the tiles' wide memory (6 x 1.07 MB): once, or again after other programs used that memory"""
    from coral.runtime import run_executable
    st = time.perf_counter()
    run_executable(self.tpu, self.caching, parameters=LY.model_params(self.Ws, self.qm))
    print(f"parameters cached on the chip: {len(LY.model_params(self.Ws, self.qm)) / 1e6:.2f} MB in {time.perf_counter() - st:.2f} s")
  def quants(self, P:int) -> list[dict]: return self.qb if P == 1 else self.qm
  def step(self, tok:int, pos:int) -> np.ndarray:
    t0, P, q = time.perf_counter(), pos + 1, self.quants(pos + 1)
    x = np.clip(np.rint(self.w["emb"][tok] / q[0]["res"][0]) + q[0]["res"][1], 0, 255).astype(np.uint8)
    cos, sin = LY.rope_inputs(pos, q[0])
    if self.mock:
      rows = lambda C: [C[l, :, :pos].transpose(1, 0, 2).reshape(pos, 288) if pos else None for l in range(self.L)]
      t1 = time.perf_counter()
      x_out, kv = LY.model_ref(x, cos, sin, rows(self.Kh), rows(self.Vh), self.Ws, q)
    else:
      buf = x.tobytes() + cos.tobytes() + sin.tobytes()
      if P > 1: buf += b"".join(self.Kh[l, :, :P].tobytes() + self.Vh[l, :, :P].tobytes() for l in range(self.L))   # row P-1: zeros
      t1 = time.perf_counter()
      from coral.runtime import run_executable
      x_out, kv = LY.model_outputs(run_executable(self.tpu, self.exes[P], buf), self.L)
    t2 = time.perf_counter()
    if self.check is not None and not self.mock:     # the bit model on the same inputs: every output must be equal
      rows = lambda C: [C[l, :, :pos].transpose(1, 0, 2).reshape(pos, 288) if pos else None for l in range(self.L)]
      rx, rkv = LY.model_ref(x, cos, sin, rows(self.Kh), rows(self.Vh), self.Ws, q)
      if not (np.array_equal(rx, x_out) and np.array_equal(rkv, kv)):
        self.bad.append(P)
        if len(self.bad) == 1:
          np.savez(f"{self.check}/stories_chip_P{P}.npz", x=x, cos=cos, sin=sin, Kh=self.Kh[:, :, :pos], Vh=self.Vh[:, :, :pos], x_out=x_out,
                   kv=kv, ref_x=rx, ref_kv=rkv)
          print(f"\n[P={P}: the device differs from the bit model: x_out {np.sum(rx != x_out)} bytes, k'|v per layer "
                f"{[int(np.sum(a != b)) for a, b in zip(rkv, kv)]} bytes; saved]", flush=True)
    self.Kh[:, :, pos], self.Vh[:, :, pos] = kv[:, :288].reshape(self.L, 6, 48), kv[:, 288:].reshape(self.L, 6, 48)
    qo = q[-1]["out"]
    h = (x_out.astype(np.float32) - qo[1]) * np.float32(qo[0])
    logits = self.out_w @ (h / np.sqrt((h * h).mean() + 1e-5) * self.norm_w)
    self.times["tpu"].append(t2 - t1); self.times["host"].append((t1 - t0) + (time.perf_counter() - t2))
    return logits

class Float:
  def __init__(self, w:dict): self.m, self.times = LY.FloatModel(w), {"tpu": [], "host": []}
  def step(self, tok:int, pos:int) -> np.ndarray:
    t0 = time.perf_counter(); lg = self.m.step(tok, pos); self.times["host"].append(time.perf_counter() - t0); return lg

def generate(model, tok:Tokenizer, prompt:str, steps:int, temperature:float=0.0, seed:int=0) -> tuple[str, int, float]:
  """the prompt through the model (filling the KV cache), then up to `steps` tokens (greedy or sampled), stopping at the next BOS ->
  (text, generated tokens, tokens/s over the generated tokens)"""
  toks, rng = tok.encode(prompt), np.random.default_rng(seed)
  out, n, st, plen = prompt, 0, None, len(toks)
  print(prompt, end="", flush=True)
  for pos in range(min(plen + steps, 256)):
    if pos == plen - 1: st = time.perf_counter()
    lg = model.step(toks[pos], pos)
    if pos < plen - 1: continue
    nxt = int(np.argmax(lg if temperature == 0 else lg / temperature + rng.gumbel(size=lg.shape)))
    if nxt == 1: break
    piece = tok.decode(toks[-1], nxt); out += piece; toks.append(nxt); n += 1
    print(piece, end="", flush=True)
  print()
  return out, n, n / (time.perf_counter() - st) if st else 0.0

if __name__ == "__main__":
  ap = argparse.ArgumentParser()
  ap.add_argument("--prompt", default="Once upon a time")
  ap.add_argument("--steps", type=int, default=200)
  ap.add_argument("--temperature", type=float, default=0.0)
  ap.add_argument("--seed", type=int, default=0)
  ap.add_argument("--mock", action="store_true", help="the bit model on the host instead of the Edge TPU")
  ap.add_argument("--float", action="store_true", help="the float model on the host")
  ap.add_argument("--eval", type=int, default=0, help="quality offline on N float stories (calibrated on 8 others)")
  ap.add_argument("--global-layout", action="store_true", help="the compiler's 1-D layout (one op per tile) instead of the tile-local one")
  ap.add_argument("--check", default=None, help="compare every device call with the bit model; save the first difference in this directory")
  args = ap.parse_args()
  cfg, w = LY.load_checkpoint()
  tok = Tokenizer(ROOT / "models/tokenizer.bin", cfg["vocab"])
  qm, qb = calibration(w)
  if args.eval:
    test = LY.float_stories(w, args.eval, 200, seed=100)
    Ws = LY.quant_weights(w, qm)
    r = LY.evaluate(w, lambda: LY.ChipModel(w, qm, qb, Ws), test)
    print(f"{r['tokens']} tokens of {args.eval} float stories: perplexity float {r['float_ppl']:.3f}, chip {r['chip_ppl']:.3f}; "
          f"the chip's argmax = the float model's {100 * r['agree']:.1f}%")
    sys.exit(0)
  max_pos = min(len(tok.encode(args.prompt)) + args.steps, 256)
  model = Float(w) if args.float else Chip(w, qm, qb, max_pos, mock=args.mock, check=args.check, local=not args.global_layout)
  kind = "float model on the host" if args.float else "bit model on the host (mock)" if args.mock else "all 6 layers on the Edge TPU, one call per token"
  print(f"--- {kind}")
  text, n, tps = generate(model, tok, args.prompt, args.steps, args.temperature, args.seed)
  t = model.times
  if args.check and not args.mock: print(f"--- bit-exact with the bit model: {len(t['tpu']) - len(model.bad)} of {len(t['tpu'])} calls"
                                         + (f" (differences at P = {model.bad[:12]}{'...' if len(model.bad) > 12 else ''})" if model.bad else ""))
  what = "bit model" if args.mock else "TPU call (USB included)"
  print(f"--- {n} tokens, {tps:.1f} tok/s" + (f"; per token: {what} {np.median(t['tpu']) * 1e3:.2f} ms (median), "
                                              f"host {np.median(t['host']) * 1e3:.2f} ms" if t["tpu"] else ""))
