# generates coral/regs.py, the chip's register names and addresses, from libedgetpu's beagle_csr_offsets.h
# (Copyright 2019 Google LLC, Apache License 2.0; clone libedgetpu into ref/ first, see README)
#   python tools/gen_regs.py
import re, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
HEADER = """# AUTOGENERATED by tools/gen_regs.py from libedgetpu's driver/config/beagle/beagle_csr_offsets.h
# (https://github.com/google-coral/libedgetpu, Copyright 2019 Google LLC, Apache License 2.0: http://www.apache.org/licenses/LICENSE-2.0).
# The register names and addresses are libedgetpu's, in a Python dict.
"""

src = (ROOT / "ref/libedgetpu/driver/config/beagle/beagle_csr_offsets.h").read_text()
def order(m) -> int:   # a name in several structs keeps its plain name in the first: the units, then breakpoints / traces / ..., debug
  return 2 if "Debug" in m.group(2) else 1 if any(x in m.group(2) for x in ("Breakpoint", "Trace", "SyncFlag", "RegisterFile")) else 0
regs = {}
for m in sorted(re.finditer(r"const (\w+) (kBeagle\w+) = \{(.*?)\};", src, re.S), key=order):
  for v, n in re.findall(r"(0x[0-9a-fA-F]+|\d+),\s*// NOLINT: (\w+)", m.group(3)):
    if regs.get(n, int(v, 0)) != int(v, 0): n = f"{m.group(2)}_{n}"
    regs[n] = int(v, 0)
out = ["REGS = {", *[f"  {n!r}: {v:#x}," for n, v in sorted(regs.items(), key=lambda x: x[1])], "}"]
(ROOT / "coral" / "regs.py").write_text(HEADER + "\n".join(out) + "\n")
print(f"{len(regs)} registers -> coral/regs.py")
